/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciosjava.datosejercicios.grupo5;

import java.io.File;

/**
 *
 * @author Sistemas
 */
public class VentanaEj1_5_rellenar extends javax.swing.JFrame {

    private final String[] listaEstudios = {"Primaria", "Secundaria", "Bachillerato", "Universidad"};

    /**
     * Creates new form Formulario
     */
    public VentanaEj1_5_rellenar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton6 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        nombreLabel = new javax.swing.JLabel();
        apellLabel = new javax.swing.JLabel();
        edadLabel = new javax.swing.JLabel();
        dniLabel = new javax.swing.JLabel();
        nombreTxtF = new javax.swing.JTextField();
        apellTxtF = new javax.swing.JTextField();
        dniTxtF = new javax.swing.JTextField();
        enviarBoton = new javax.swing.JButton();
        estadoCivLabel = new javax.swing.JLabel();
        estudSupLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cCheckBox = new javax.swing.JCheckBox();
        javaCheckBox = new javax.swing.JCheckBox();
        csharpCheckBox = new javax.swing.JCheckBox();
        javascriptCheckBox = new javax.swing.JCheckBox();
        edadJSpinner = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        solteroRadio = new javax.swing.JRadioButton();
        casadoRadio = new javax.swing.JRadioButton();
        estudiosCombo = new javax.swing.JComboBox<>();
        estudSupLabel1 = new javax.swing.JLabel();
        rellenarBoton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Soltero");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(309, 349));

        nombreLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nombreLabel.setText("Nombre: ");

        apellLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        apellLabel.setText("Apellidos:");

        edadLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        edadLabel.setText("Edad: ");

        dniLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dniLabel.setText("DNI: ");

        nombreTxtF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        apellTxtF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        dniTxtF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        enviarBoton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        enviarBoton.setText("Enviar");
        enviarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarBotonActionPerformed(evt);
            }
        });
        enviarBoton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                enviarBotonKeyTyped(evt);
            }
        });

        estadoCivLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        estadoCivLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        estadoCivLabel.setText("Estado civil: ");

        estudSupLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        estudSupLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        estudSupLabel.setText("Estudios ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lenguajes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        cCheckBox.setText("C");

        javaCheckBox.setText("Java");

        csharpCheckBox.setText("C#");

        javascriptCheckBox.setText("JavaScript");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(javaCheckBox)
                    .addComponent(cCheckBox))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(javascriptCheckBox)
                    .addComponent(csharpCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(csharpCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(javascriptCheckBox))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(javaCheckBox)))
                .addContainerGap())
        );

        edadJSpinner.setModel(new javax.swing.SpinnerNumberModel(20, 18, 80, 1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Datos usuario");

        buttonGroup1.add(solteroRadio);
        solteroRadio.setText("Soltero");

        buttonGroup1.add(casadoRadio);
        casadoRadio.setText("Casado");

        estudiosCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige estudios", "Primaria", "Secundaria", "Bachiller", "Cou", "Universidad" }));

        estudSupLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        estudSupLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        estudSupLabel1.setText("superiores:");

        rellenarBoton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rellenarBoton.setText("Rellenar");
        rellenarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rellenarBotonActionPerformed(evt);
            }
        });
        rellenarBoton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rellenarBotonKeyTyped(evt);
            }
        });

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenu1.setText("Rellenar Datos  ");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda  ");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enviarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rellenarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dniLabel)
                                            .addComponent(apellLabel)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(nombreLabel)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nombreTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(apellTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(dniTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(edadLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(edadJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(estudSupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(estudSupLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(estudiosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(estadoCivLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(casadoRadio)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(solteroRadio))))))
                            .addComponent(jLabel9))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dniLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dniTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edadLabel)
                            .addComponent(edadJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoCivLabel)
                    .addComponent(casadoRadio)
                    .addComponent(solteroRadio))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(estudSupLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estudSupLabel1)
                            .addComponent(estudiosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rellenarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(enviarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        estudSupLabel.getAccessibleContext().setAccessibleName("Estudios superiores: ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarBotonActionPerformed
        enviarFormulario();
        guardarFormulario();
    }//GEN-LAST:event_enviarBotonActionPerformed

    private void enviarBotonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enviarBotonKeyTyped
        enviarFormulario();
        guardarFormulario();
    }//GEN-LAST:event_enviarBotonKeyTyped

    private void rellenarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rellenarBotonActionPerformed
        nombreTxtF.setText("Rafael");
        apellTxtF.setText("Martínez Costas");
        dniTxtF.setText("333444555-J");
        edadJSpinner.setValue(25);
        casadoRadio.setSelected(true);
        estudiosCombo.setSelectedItem("Cou");
        cCheckBox.setSelected(true);
        javascriptCheckBox.setSelected(true);

    }//GEN-LAST:event_rellenarBotonActionPerformed

    private void rellenarBotonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rellenarBotonKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_rellenarBotonKeyTyped
    private void enviarFormulario() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                boolean casado;
                boolean[] lenguages = {false, false, false, false};

                if (casadoRadio.isSelected()) {
                    casado = true;
                } else {
                    casado = false;
                }
                if (javaCheckBox.isSelected()) {
                    lenguages[0] = true;
                }
                if (cCheckBox.isSelected()) {
                    lenguages[1] = true;
                }
                if (csharpCheckBox.isSelected()) {
                    lenguages[2] = true;
                }
                if (javascriptCheckBox.isSelected()) {
                    lenguages[3] = true;
                }

                new VentanaEj1_5_mostrar(
                        nombreTxtF.getText(),
                        apellTxtF.getText(),
                        dniTxtF.getText(),
                        estudiosCombo.getSelectedItem().toString(),
                        Integer.parseInt(edadJSpinner.getValue().toString()),
                        casado,
                        lenguages
                ).setVisible(true);

            }
        });

    }

    private void guardarFormulario() {
        System.out.println("\nGUARDANDO DATOS EN ARCHIVO");
        //CREAR CARPETA
        //Definimos directorio donde queremos los datos
        String nombreArchivo;
        File carpeta;
        carpeta = new File("TextosCreados");

        //Comprobamos si existe esa carpeta y si no la creamos
        if (carpeta.exists()) {
            System.out.println("Carpeta ya existe");
        } else {
            //intentamos crearla
            if (carpeta.mkdirs()) {
                System.out.println("Carpeta " + carpeta.getName() + " creada.");
            }else{
                System.out.println("Problema al crear carpeta.");
            }
        }
        //CREAR ARCHIVO
        //Definimos nombre del archivo a crear
        nombreArchivo= "formulario.txt";
        //Definimos ruta con nombre del archivo
        File archivo=new File(carpeta,nombreArchivo);
        
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEj1_5_rellenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEj1_5_rellenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEj1_5_rellenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEj1_5_rellenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEj1_5_rellenar().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellLabel;
    private javax.swing.JTextField apellTxtF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cCheckBox;
    private javax.swing.JRadioButton casadoRadio;
    private javax.swing.JCheckBox csharpCheckBox;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JTextField dniTxtF;
    private javax.swing.JSpinner edadJSpinner;
    private javax.swing.JLabel edadLabel;
    private javax.swing.JButton enviarBoton;
    private javax.swing.JLabel estadoCivLabel;
    private javax.swing.JLabel estudSupLabel;
    private javax.swing.JLabel estudSupLabel1;
    private javax.swing.JComboBox<String> estudiosCombo;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JCheckBox javaCheckBox;
    private javax.swing.JCheckBox javascriptCheckBox;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTxtF;
    private javax.swing.JButton rellenarBoton;
    private javax.swing.JRadioButton solteroRadio;
    // End of variables declaration//GEN-END:variables
}
