/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciosjava.datosejercicios.grupo5;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Sistemas
 */
public class VentanaEj2_5 extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEj2_5
     */
    public VentanaEj2_5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textoTXTAREA = new javax.swing.JTextArea();
        fileNameTXTFIELD = new javax.swing.JTextField();
        pathTXTFIELD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buscarBOTON = new javax.swing.JButton();
        modoGrabarCOMBOBOX = new javax.swing.JComboBox<>();
        guardarDirectBOTON = new javax.swing.JButton();
        leerBOTON = new javax.swing.JButton();
        cerrarBOTON = new javax.swing.JButton();
        GuardarComoBOTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ejercicio2_Ficheros");

        textoTXTAREA.setColumns(20);
        textoTXTAREA.setRows(5);
        jScrollPane1.setViewportView(textoTXTAREA);

        fileNameTXTFIELD.setText("miArchivo.txt");
        fileNameTXTFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameTXTFIELDActionPerformed(evt);
            }
        });

        pathTXTFIELD.setText("TextosCreados/");

        jLabel1.setText("Nombre archivo: ");

        jLabel2.setText("Ruta al archivo (raiz proyecto): ");

        buscarBOTON.setText("Buscar archivo");
        buscarBOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBOTONActionPerformed(evt);
            }
        });

        modoGrabarCOMBOBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Añadir texto", "Sustituir texto" }));

        guardarDirectBOTON.setText("Guardar archivo");
        guardarDirectBOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarDirectBOTONActionPerformed(evt);
            }
        });

        leerBOTON.setText("Leer archivo");
        leerBOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerBOTONActionPerformed(evt);
            }
        });

        cerrarBOTON.setText("Cerrar");
        cerrarBOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarBOTONActionPerformed(evt);
            }
        });

        GuardarComoBOTON.setText("Guardar como");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileNameTXTFIELD)
                            .addComponent(pathTXTFIELD, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cerrarBOTON, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modoGrabarCOMBOBOX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(leerBOTON, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarBOTON, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(guardarDirectBOTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GuardarComoBOTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileNameTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(2, 2, 2)
                .addComponent(modoGrabarCOMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarComoBOTON)
                    .addComponent(buscarBOTON))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarDirectBOTON)
                    .addComponent(leerBOTON))
                .addGap(18, 18, 18)
                .addComponent(cerrarBOTON, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileNameTXTFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameTXTFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileNameTXTFIELDActionPerformed

    private void guardarDirectBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarDirectBOTONActionPerformed
        String texto = textoTXTAREA.getText();
        File rutaArch = new File(pathTXTFIELD.getText());
        String nombreArch = fileNameTXTFIELD.getText();
        File archivo = new File(rutaArch, nombreArch);
        if (!rutaArch.exists()) {
            System.out.println("La ruta no existe. La creamos");
            rutaArch.mkdirs();
        }
        if (!archivo.exists()) {
            System.out.println("El archivo no existe. Lo creamos");
            try {
                rutaArch.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(VentanaEj2_5.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        //Abrimos fichero para escritura
        FileWriter archivoWrite = null;
        PrintWriter pw = null;
        System.out.println(modoGrabarCOMBOBOX.getSelectedIndex());
        try {

            if (modoGrabarCOMBOBOX.getSelectedIndex() == 0) {
                archivoWrite = new FileWriter(archivo, true);
                pw = new PrintWriter(archivoWrite);
            } else {
                archivoWrite = new FileWriter(archivo);
                pw = new PrintWriter(archivoWrite);
            }
            System.out.println(texto);
            pw.print(texto);
        } catch (IOException ex) {
            Logger.getLogger(VentanaEj2_5.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                //  aprovechamos el finally para asegurarnos que se cierra el fichero.
                if (null != archivoWrite) {
                    archivoWrite.close();
                }
            } catch (IOException e2) {
                System.out.println(e2.getMessage());
            }
        }

    }//GEN-LAST:event_guardarDirectBOTONActionPerformed

    private void leerBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerBOTONActionPerformed
        String texto = textoTXTAREA.getText();
        File rutaArch = new File(pathTXTFIELD.getText());
        String nombreArch = fileNameTXTFIELD.getText();
        File archivo = new File(rutaArch, nombreArch);
        FileReader archivoRead = null;
        BufferedReader bufferLectura;
        try {
            archivoRead = new FileReader(archivo);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VentanaEj2_5.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (archivo.exists()) {
            if (archivo.canRead()) {
                bufferLectura = new BufferedReader(archivoRead);
                String linea;
                textoTXTAREA.setText("");
                try {
                    while ((linea = bufferLectura.readLine()) != null) {
                        System.out.println(linea);
                        textoTXTAREA.append(linea + "\n");
                    }
                } catch (IOException ex) {
                    Logger.getLogger(VentanaEj2_5.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                System.out.println("no tiene permiso para leer ese archivo");
            }

        } else {
            System.out.println("Ese archivo no existe");
        }
    }//GEN-LAST:event_leerBOTONActionPerformed

    private void cerrarBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarBOTONActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarBOTONActionPerformed

    private void buscarBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBOTONActionPerformed
        JFileChooser searchFile = new JFileChooser();
        File selectedFile;
        File originalPath = new File("C:\\cygwin64\\home\\Sistemas\\proj\\IFCT0609\\Java\\!!Definitivo\\IFCT0609EjerciciosJava\\"); // ./ es la ruta en la que se ejecuta programa
        searchFile.setCurrentDirectory(originalPath);
        if (searchFile.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            selectedFile = searchFile.getSelectedFile();
            System.out.println("[proj]\\" + getRelativePath(selectedFile, originalPath));
            fileNameTXTFIELD.setText(selectedFile.getName());
            pathTXTFIELD.setText(getRelativePath(selectedFile, originalPath));
        }


    }//GEN-LAST:event_buscarBOTONActionPerformed
    /**
     * Halla la ruta relativa a una carpeta
     * @param file File Archivo de referencia
     * @param folder carpeta relativa
     */    
    public static String getRelativePath(File file, File folder) {
        String filePath = file.getAbsolutePath();
        int fileName = file.getName().length();
        String folderPath = folder.getAbsolutePath();
        String relativePath;

        if (filePath.startsWith(folderPath)) {
            //borra la ruta hasta la carpeta de referencia
            relativePath = filePath.substring(folderPath.length() + 1);
            //borra el nombre del archivo
            relativePath = relativePath.substring(0, relativePath.length() - fileName);
            System.out.println("Ruta relativa: "+ relativePath);
            return relativePath;
        } else {
            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEj2_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEj2_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEj2_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEj2_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEj2_5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuardarComoBOTON;
    private javax.swing.JButton buscarBOTON;
    private javax.swing.JButton cerrarBOTON;
    private javax.swing.JTextField fileNameTXTFIELD;
    private javax.swing.JButton guardarDirectBOTON;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leerBOTON;
    private javax.swing.JComboBox<String> modoGrabarCOMBOBOX;
    private javax.swing.JTextField pathTXTFIELD;
    private javax.swing.JTextArea textoTXTAREA;
    // End of variables declaration//GEN-END:variables
}
